# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acfe307082cf5c179f9abed4fece268784192171139a628df0fd7fb58759522bf9297e1cbcdafda793784563b7cdfce7081350e2fc5298214f46dfe14463451e

test:
  secret_key_base: b9a99b5d7ef034417137e0611aec8278d5d5dba35d1ef08b58a31a7ac19ffe57fc204ade855acd4f340cd35efec1049e819410a79c6a51775b04bca9ba6dc1de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b9a99b5d7ef034417137e0611aec8278d5d5dba35d1ef08b58a31a7ac19ffe57fc204ade855acd4f340cd35efec1049e819410a79c6a51775b04bca9ba6dc1de
